config/routes.rb
Rails.application.routes.draw do
  root 'concierge#index'
  get 'concierge/index'

  resources :concierge do
    member do
      get :store_bag
      get :retrieve_bag
    end
  end

end

app/models/bag.rb
class Bag < ActiveRecord::Base
  belongs_to :locker
  scope :small, -> { where(size: 'small') }
  scope :medium, -> { where(size: 'medium') }
  scope :large, -> { where(size: 'large') }
  scope :checked, -> { where.not(locker_id: nil) }
  scope :unchecked, -> { where(locker_id: nil) }
end

app/models/locker.rb
class Locker < ActiveRecord::Base
  has_one :bag
  scope :small, -> { where(size: 'small') }
  scope :medium, -> { where(size: 'medium') }
  scope :large, -> { where(size: 'large') }
  scope :empty, -> { where.not(id: Bag.pluck(:locker_id).uniq) }
  scope :full, -> { where(id: Bag.pluck(:locker_id).uniq) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bag_controller.rb
class BagController < ApplicationController
end

app/controllers/concierge_controller.rb
class ConciergeController < ApplicationController
  def index
    @locker = Locker.all
    @bag = Bag.all
    @random_guest_bag = Bag.unchecked.first if Bag.unchecked.exists?
    if Bag.checked.exists?
      @random_guest_ticket = Bag.checked.all.order('random()').first
    else
      @bag = Bag.small.first
      @bag.update_attributes(locker_id: 1)
      @random_guest_ticket = Bag.checked.all.order('random()').first if @bag.save
      flash[:notice] = "This is the General Manager's gym bag - please do not remove it."
      flash[:alert] = nil
    end
  end

  def store_bag
    if Locker.empty.count == 0
      respond_to do |format|
        format.html { redirect_to(:root, alert: "There are no more empty lockers - please go to the Venetian Casino, where they can check your bag."   
          )}
      end    
    else
      check_bag
    end
  end

  def check_bag
    @bag = Bag.find(params[:id])
    if @bag.size == 'small'
      if Locker.small.empty.exists?
        locker_id = Locker.small.empty.first.id
      elsif Locker.medium.empty.exists?
        locker_id = Locker.medium.empty.first.id
      elsif Locker.large.empty.exists?
        locker_id = Locker.large.empty.first.id
      else
        flash[:notice] = "We don't have any open lockers."
      end
    end
    if @bag.size == 'medium'
      if Locker.medium.empty.exists?
        locker_id = Locker.medium.empty.first.id
      elsif Locker.large.empty.exists?
        locker_id = Locker.large.empty.first.id
      else
        flash[:notice] = "We don't have any open lockers."
      end
    end
    if @bag.size == 'large'
      if Locker.large.empty.exists?
        locker_id = Locker.large.empty.first.id
      else
        flash[:notice] = "We don't have any open lockers."
       end
    end
    @bag.update_attributes(locker_id: locker_id)
    if @bag.save
    	ticket = Locker.where(id: locker_id).first.id.to_s
      respond_to do |format|
        format.html { redirect_to(
        	root_path(ticket: ticket), 
        	notice: 'Please check this bag into locker #' + Locker.where(id: locker_id).first.id.to_s + ', which is a ' + Locker.where(id: locker_id).first.size.to_s + ' locker.')
      }
      end
    end
  end

  def retrieve_bag
    @bag = Bag.find(params[:id])
    locker_id = Bag.find(params[:id]).locker_id
    @bag.update_attributes(locker_id: nil)
    if @bag.save
      respond_to do |format|
        format.html { 
        	redirect_to(
        		:root, 
        		alert: 'Great! The bag was successfully returned from locker #' + 
        			Locker.where(id: locker_id).first.id.to_s + 
      				', which was a ' + 
      				Locker.where(id: locker_id).first.size.to_s + 
      				' locker.'
        	)
        }
      end
    end
  end
end

app/controllers/locker_controller.rb
class LockerController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bag_helper.rb
module BagHelper
end

app/helpers/concierge_helper.rb
module ConciergeHelper
end

app/helpers/locker_helper.rb
module LockerHelper
end

app/views/concierge/index.html.erb
<div class="row">
	<div class="large-3 columns">
		<%= image_tag('concierge.jpg', :id => "concierge") %>
	</div>
	<div class="large-9 columns">
		<h4 id="concierge_headline">What would you like to do?</h4>
		<div class="large-4 columns">
			<%= link_to('Store Bag', store_bag_concierge_path(id: @random_guest_bag.id), :id => "store_bag_button", :class => "button success") %>
			<div id="store_bag_details"> 			
				<h5>Bag Size: <span><%= @random_guest_bag.size %></span></h5>	
			</div>
		</div>	
		<div class="large-4 columns">
			<%= link_to('Retrieve Bag', retrieve_bag_concierge_path(id: @random_guest_ticket.id), :id => "retrieve_bag_button", :class => "button") %>
			<div id="retrieve_bag_details"> 
				<h5>Customer Ticket: <span><%= @random_guest_ticket.locker_id %></span></h5>
				<h5>Bag Size: <span><%= @random_guest_ticket.size %></span></h5>
			</div>
		</div>
		<div class="large-1 columns"></div>
	</div>
</div>
<hr>
<div class="row">
	<div class="large-8 columns large-centered">
		<h4>Current Locker Status:</h4>
		<table id="data_table" style="width:100%;text-align:center;">
			<thead>
				<tr>
					<th>Locker Size</th>
					<th>Empty</th>
					<th>Filled</th>		
					<th>Total</th>
				</tr>
			<thead>
			<tbody>
				<tr>
					<td>Small Locker</td>
					<td><%= @locker.small.empty.count %></td>
					<td><%= @locker.small.full.count %></td>
					<td><%= @locker.small.count %></td>
				</tr>
				<tr>
					<td>Medium Locker</td>
					<td><%= @locker.medium.empty.count %></td>
					<td><%= @locker.medium.full.count %></td>
					<td><%= @locker.medium.count %></td>
				</tr>
				<tr>
					<td>Large Locker</td>
					<td><%= @locker.large.empty.count %></td>
					<td><%= @locker.large.full.count %></td>
					<td><%= @locker.large.count %></td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<th colspan="1">Total :</th>
					<strong><td><%= @locker.empty.count %></td></strong>
					<strong><td><%= @locker.full.count %></td></strong>
					<strong><td><%= @locker.count %></td></strong>
				</tr>
			</tfoot>
		</table>
	</div>
</div>
<hr>
<div class="row">
	<div class="large-8 columns large-centered">
		<h4>Customer Ticket for Checked Bags:</h4>
		<table id="data_table" style="width:100%;text-align:center;">
			<thead>
				<tr>
					<th>Customer Ticket# 
							<% if params[:ticket] %>
								<span id="customer_ticket">
									<%= params[:ticket] %>
							    </span>
							<% end %>
					</th>
				</tr>
			<thead>
			<tbody>
				<tr>
					<td>Thank you for visiting our concierge desk. Please present this ticket to the concierge to retrieve your checked baggage. <p><em>It is our pleasure to serve you.</em></p></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">LockerTracker</a></h1>
        </li>
      </ul>

      <section class="top-bar-section">
      </section>
    </nav>
    <div id="notice_container">
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>

  </body>
</html>